name: Publish Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
jobs:
  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  linux_release:
    name: Linux Release
    needs: publish_release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with: 
        python-version: "3.11"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build by Pyinstaller
      run: |
        pyinstaller -F -n cpu_network_auth src/main.py
    - name: Arrange Files
      run: |
        chmod +x ./dist/cpu_network_auth
        mkdir ./release/
        mkdir ./release/CPU_Network_Auth_Linux/
        cd ./release/CPU_Network_Auth_Linux/
        cp ../../dist/cpu_network_auth .
        cp ../../config.txt .
    - name: Zip Files
      run: |
        cd ./release
        zip -r ./CPU_Network_Auth_Linux.zip ./CPU_Network_Auth_Linux/
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.publish_release.outputs.upload_url }}
        asset_path: ./release/CPU_Network_Auth_Linux.zip
        asset_name: CPU_Network_Auth_Linux.zip
        asset_content_type: application/zip
  windows_release:
    name: Windows Release
    needs: publish_release
    runs-on: windows-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with: 
        python-version: "3.11"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        choco install zip
    - name: Build by Pyinstaller
      run: |
        pyinstaller -F -n cpu_network_auth.exe src/main.py
    - name: Arrange Files
      run: |
        mkdir ./release/
        mkdir ./release/CPU_Network_Auth_Windows/
        cd ./release/CPU_Network_Auth_Windows/
        cp ../../dist/cpu_network_auth.exe .
        cp ../../config.txt .
    - name: Zip Files
      run: |
        cd ./release
        zip -r ./CPU_Network_Auth_Windows.zip ./CPU_Network_Auth_Windows/
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.publish_release.outputs.upload_url }}
        asset_path: ./release/CPU_Network_Auth_Windows.zip
        asset_name: CPU_Network_Auth_Windows.zip
        asset_content_type: application/zip
